# Site settings
title: Luke Browning
email:
description: Luke Browning > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://luke.browning.io" # the base hostname & protocol for your site

twitter_username: lukebrowning
github_username: lukasbrowning
linkedin_username: lukejbrowning
facebook_username: luke.browning
instagram_username: lukasbrowning

# Build settings
markdown: kramdown
